server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/Blext66/microservices-curso
          search-paths: config-data
  application:
    name: config-service